# Generated by Django 5.2.12 on 2026-04-03 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EndOfLife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=50, unique=True)),
                ('subtype', models.CharField(blank=True, max_length=100)),
                ('eco_cost', models.FloatField()),
                ('carbon_kg', models.FloatField()),
                ('unit', models.CharField(default='kg', max_length=50)),
            ],
            options={
                'db_table': 'end_of_life',
            },
        ),
        migrations.CreateModel(
            name='Energy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=50, unique=True)),
                ('subtype', models.CharField(blank=True, max_length=100)),
                ('eco_cost', models.FloatField()),
                ('carbon_kg', models.FloatField()),
                ('unit', models.CharField(default='kWh', max_length=50)),
            ],
            options={
                'db_table': 'energy',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=50, unique=True)),
                ('subtype', models.CharField(blank=True, max_length=100)),
                ('eco_cost', models.FloatField()),
                ('carbon_kg', models.FloatField()),
                ('unit', models.CharField(default='kg', max_length=50)),
            ],
            options={
                'db_table': 'material',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=50, unique=True)),
                ('subtype', models.CharField(blank=True, max_length=100)),
                ('eco_cost', models.FloatField()),
                ('carbon_kg', models.FloatField()),
                ('unit', models.CharField(default='unit', max_length=50)),
            ],
            options={
                'db_table': 'production',
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'scenario',
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=50, unique=True)),
                ('subtype', models.CharField(blank=True, max_length=100)),
                ('eco_cost', models.FloatField()),
                ('carbon_kg', models.FloatField()),
                ('unit', models.CharField(default='km', max_length=50)),
            ],
            options={
                'db_table': 'transport',
            },
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('eco_cost', models.FloatField()),
                ('carbon_kg', models.FloatField()),
            ],
            options={
                'db_table': 'usage',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='ImpactResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_eco_cost', models.FloatField(default=0)),
                ('total_carbon_kg', models.FloatField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.scenario')),
            ],
            options={
                'db_table': 'impact_result',
            },
        ),
        migrations.CreateModel(
            name='EndOfLifeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=1)),
                ('end_of_life', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.endoflife')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
            options={
                'db_table': 'end_of_life_product',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('impact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.impactresult')),
            ],
            options={
                'db_table': 'recommendation',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='default_scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.scenario'),
        ),
        migrations.CreateModel(
            name='ScenarioEndOfLife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=1)),
                ('end_of_life', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.endoflife')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.scenario')),
            ],
            options={
                'db_table': 'scenario_end_of_life',
            },
        ),
        migrations.CreateModel(
            name='ScenarioEnergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=1)),
                ('energy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.energy')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.scenario')),
            ],
            options={
                'db_table': 'scenario_energy',
            },
        ),
        migrations.CreateModel(
            name='ScenarioProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=1)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.production')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.scenario')),
            ],
            options={
                'db_table': 'scenario_production',
            },
        ),
        migrations.CreateModel(
            name='ScenarioTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(default=0)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.scenario')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.transport')),
            ],
            options={
                'db_table': 'scenario_transport',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.CreateModel(
            name='ScenarioMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=1)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.material')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.scenario')),
            ],
            options={
                'db_table': 'scenario_material',
                'unique_together': {('scenario', 'material')},
            },
        ),
    ]
