# Generated by Django 5.2.12 on 2026-04-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariomaterial',
            name='is_packaging',
            field=models.BooleanField(default=False),
        ),
    ]
