# Generated by Django 4.2.6 on 2026-05-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_restructure_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
